---
- hosts: prod
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Run/restart docker compose
      docker_service:
        project_src: "/var/www/nodejs/releases/20190915122540/"
      restarted: yes