---
- hosts: prod
  vars:
    - project_path: /var/www/nodejs
    - homeDir: /home/ubuntu
  tasks:
    - name: Set some variable
      set_fact:
        release_path: "{{ project_path }}/releases/{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
        current_path: "{{ project_path }}/current"
    - name: Retrieve current release folder
      command: readlink -f current
      register: current_release_path
      ignore_errors: yes
      args:
        chdir: "{{ project_path }}"
    - name: Create new folder
      file:
        dest={{ release_path }}
        mode=0755
        recurse=yes
        state=directory
    - name: Copy Private Key
      copy: src="/home/hkothari/.ssh/id_rsa" dest={{homeDir}} mode=0600
    - name: Clone the repository
      git: repo="https://github.com/HemaSree1519/SaveNoteApp.git" dest={{ release_path }} update=yes force=yes accept_hostkey=yes key_file={{homeDir}}/id_rsa

