- hosts: prod
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: Install jdk
      apt:
        name: default-jdk
        state: latest